# Generated by Django 4.1.7 on 2023-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_log_picture_alter_log_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='picture',
            field=models.ImageField(upload_to='logs/image/'),
        ),
    ]
