# Generated by Django 4.1.7 on 2023-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_number',
            field=models.ImageField(default=34, upload_to=''),
            preserve_default=False,
        ),
    ]
