# Generated by Django 4.1.7 on 2023-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block_number',
            field=models.IntegerField(),
        ),
    ]
