# Generated by Django 4.1.7 on 2023-04-02 15:24

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_profile_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=userprofile.models.get_upload_path),
        ),
    ]
