# Generated by Django 4.1.7 on 2023-04-02 15:52

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='image', upload_to=userprofile.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='2', upload_to=userprofile.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image4',
            field=models.ImageField(default=2, upload_to=userprofile.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image5',
            field=models.ImageField(default=2, upload_to=userprofile.models.get_upload_path),
            preserve_default=False,
        ),
    ]
