# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from userprofile.models import Profile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webCamFeed = QtWidgets.QLabel(self.centralwidget)
        self.webCamFeed.setGeometry(QtCore.QRect(20, 30, 481, 361))
        self.webCamFeed.setAutoFillBackground(False)
        self.webCamFeed.setStyleSheet("background:rgb(222, 219, 219);\n"
                                      "border-style:solid;\n"
                                      "border-width:5;\n"
                                      "border-color:brown;")
        self.webCamFeed.setTextFormat(QtCore.Qt.RichText)
        self.webCamFeed.setAlignment(QtCore.Qt.AlignCenter)
        self.webCamFeed.setObjectName("webCamFeed")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 30, 221, 112))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.DateTimeGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.DateTimeGrid.setContentsMargins(0, 0, 0, 0)
        self.DateTimeGrid.setObjectName("DateTimeGrid")
        self.timeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.timeLabel.setFont(font)
        self.timeLabel.setTextFormat(QtCore.Qt.RichText)
        self.timeLabel.setObjectName("timeLabel")
        self.DateTimeGrid.addWidget(self.timeLabel, 1, 0, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.dateLabel.setFont(font)
        self.dateLabel.setTextFormat(QtCore.Qt.RichText)
        self.dateLabel.setObjectName("dateLabel")
        self.DateTimeGrid.addWidget(self.dateLabel, 0, 0, 1, 1)
        self.date = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display")
        font.setPointSize(22)
        self.date.setFont(font)
        self.date.setTextFormat(QtCore.Qt.AutoText)
        self.date.setObjectName("date")
        self.DateTimeGrid.addWidget(self.date, 0, 1, 1, 1)
        self.time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display")
        font.setPointSize(22)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.DateTimeGrid.addWidget(self.time, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(510, 160, 271, 371))
        self.groupBox.setStyleSheet("backgroud:red;")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 231, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.blockLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.blockLabel.setObjectName("blockLabel")
        self.gridLayout.addWidget(self.blockLabel, 1, 0, 1, 1)
        self.block = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.block.setObjectName("block")
        self.gridLayout.addWidget(self.block, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 450, 88, 34))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.webCamFeed.setText(_translate("MainWindow", "Image"))
        self.timeLabel.setText(_translate("MainWindow", "Time:"))
        self.dateLabel.setText(_translate("MainWindow", "Date:"))
        self.date.setText(_translate("MainWindow", "-"))
        self.time.setText(_translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "Details"))
        self.name.setText(_translate("MainWindow", "-"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.blockLabel.setText(_translate("MainWindow", "Block:"))
        self.block.setText(_translate("MainWindow", "-"))
        self.pushButton.setText(_translate("MainWindow", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
